### ISSUE TITLE
Non english and RTL text

### ISSUE THREAD

**Issue by husayt** [ajitid/fzf-for-js#112]
I was  wondering if this library supports non latin alphabets (e.g. greek, cyrillic) or even RTL text (e.g. arabic)

Thanks

**Comment by ajitid** [comment]
Hey. It supports Unicode if that's what you are wondering.  Here's something I typed in Devanagari (Hindi), and it seems to work:

![image](https://user-images.githubusercontent.com/26769888/204376878-1ec9d022-f10e-4f12-8cea-d83a81136205.png)

I can't guarantee about RTL. Could you try it out and respond back here?

**Comment by husayt** [comment]
Thanks.  I will let you know
