### ISSUE TITLE
NOT sort by score option

### ISSUE THREAD

**Issue by peterbe** [ajitid/fzf-for-js#28]
The [`find` method](https://github.com/ajitid/fzf-for-js/blob/359e2b9e190dc4f4a1babcdcb63073f44a8f35b4/src/lib/main.ts#L138) always sorts by `.score`. 
What I need is that it doesn't sort at all but leaves the order of the original `list`. 

So, looking at the [Basic usage](https://fzf.netlify.app/#basic-usage) that example returns:
```
Output: lisp, kotlin, elixir
```
but what I need it to be is:
```
Output: kotlin, elixir, lisp
```
because that's the order they appear in the `list` option:
```js
const list = ['go', 'javascript', 'python', 'rust', 
              'swift', 'kotlin', 'elixir', 'java', 
              'lisp', 'v', 'zig', 'nim', 'rescript', 
              'd', 'haskell']
```

The reason for needing this is that my list that I search on are sorted by "popularity". 
If the user only type something really short like `f` I really want to favor the popular items first because the assumed likelihood that it's what the user expects to find. 

So ideal would be something like:
```ts
const entries = fzf.find('li', {sort: (item) => item})
```
or 
```ts
const entries = fzf.find('li', {sortByScore: false})
```
so that it only "filters" the list.

**Comment by peterbe** [comment]
To give context, on [MDN Web docs](https://developer.mozilla.org/en-US/) you can fuzzy search the document URIs by starting your autocomplete search with a `/` character (and no spaces).
<img width="404" alt="Screen Shot 2021-07-27 at 8 25 19 PM" src="https://user-images.githubusercontent.com/26739/127244255-696607e3-c699-4f9c-a24b-4b677c8e7dc3.png">

Try the full Elasticsearch search: https://developer.mozilla.org/en-US/search?q=foreach
There are a lot of documents that match that but it seems most people are looking for [this one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) according to our pageviews analytics. 

But our current implementation isn't great and `fzf` looks like a really good candidate to move to.

**Comment by ajitid** [comment]
Hi @peterbe! Optionally providing a sorter is something that I do have in mind and is already [noted here (first point)](https://github.com/ajitid/fzf-for-js/issues/2). There are few perf related experiments that I'm doing, after which this task will be picked up.

> our current implementation isn't great

What issues are you facing with the current implementation? Is it fuzzy matching, less relevant results on searching document URIs, performance or something else? 

Also, could you please point me to the code where the current fuzzy finding implementation is written?

**Comment by peterbe** [comment]
> Also, could you please point me to the code where the current fuzzy finding implementation is written?

It's here: https://github.com/mdn/yari/blob/main/client/src/fuzzy-search.ts
It's quite a mouthful because our code is called `fuzzy-search.ts` and it depends on 2 third-party libraries: 

- `fuzzysearch`
- `fuzzyjs`

One of them is fast and I use that to reduce down the list of 10,000+ strings down to 1,000 strings. That weeds out the ones that don't even match. Then, the second one is used to get the positions so that I can build the React code for highlighting. 

My hope is that `fzf` could replace almost all of that *and* generally yield better results.

My very very rough experimentation with switch to `fzf` is here: https://github.com/mdn/yari/compare/main...peterbe:experimenting-with-fzf-for-fuzzy-search

**Comment by peterbe** [comment]
> What issues are you facing with the current implementation? Is it fuzzy matching, less relevant results on searching document URIs, performance or something else?

Yeah, relevance. I'd rather display the "best" document ahead of any that "matches" better. 
We're doing the same with our full site-search. There, you can actually change the sort order between "best", "relevance", and "popularity" where "best" means a combination of "relevance" and "popularity". 
See [sample search](https://developer.mozilla.org/en-US/search?q=array+buffer&debug)

VSCode does something similar and different. 
<img width="748" alt="Screen Shot 2021-07-28 at 9 30 23 AM" src="https://user-images.githubusercontent.com/26739/127330791-bc4b73a7-8c80-494e-98cb-078a7bc0a3b0.png">
There, they make two result lists: recently opened files, all other files. 
But in this example, they show `testing.yml` ahead of `package.json` (both contain `g`) because I think I touched `testing.yml` more recently which is how I think they rank "popularity".

**Comment by peterbe** [comment]
Funny and timely! I just discovered a bug in our existing code (that doesn't use `fzf`). 
I filed this for ourselves: https://github.com/mdn/yari/issues/4346
I don't know how or where it regressed but I'll need to worry about that a little.

**Comment by peterbe** [comment]
Ok. So I set down to try to figure out what the heck is going on with https://github.com/mdn/yari/issues/4346 and how I can fix it with the existing stack. 
Then it occurred to me, why not try to jump over to `fzf` straight away it already seems more powerful and convenient. 
So I cooked up https://github.com/mdn/yari/pull/4347

@ajitid I know it's a big ask but would you be interested in helping to review that. Or at least test it or give it a quick look-over. 
The mdn/yari repo is the public (MPL-2.0) repo for [MDN Web Docs](https://developer.mozilla.org).

**Comment by ajitid** [comment]
Reviewed it and the code looks fine.

From https://github.com/mdn/yari/pull/4347#issue-698828161:

> I realized I had to rewrite how we use fuzzyjs but I've also experimented with fzf and it's proven to be very performant.

I won't be able to confirm as I haven't tested fzf against fuzzyjs + fuzzysearch though I've seen some initial tests [done here](https://github.com/peterbe/yari/commit/682982633bf0c3f6c8edab0883061642552d86c4#diff-5a7bf9425a67fceb3a7c4455080a3d3c23a2bb0ad375c1549557ce58eb72fb23R221).

**Comment by peterbe** [comment]
That was not a fair comparison for the record. :)

By the way, I think contributing a PR to this code base would be very feasible now that I've browsed the code a bit. 
But it would be nice to have your "blessing" in what *you* think the new option should be called. Some options:

- `sortByScore: boolean`
- `sort` override
- `disableSortByScore: boolean`

**Comment by ajitid** [comment]
I'm already working on a branch https://github.com/ajitid/fzf-for-js/tree/feat/skip-score-sorting that will add a boolean `sort`.

**Comment by ajitid** [comment]
`sort` option is now available in v0.3.2. This can be used to disable sorting by score:

```js
const fzf = new Fzf(list, {
  sort: false
})
```

**Comment by ajitid** [comment]
> I think contributing a PR to this code base would be very feasible 

Thanks @peterbe! While we've merged the (sort) feature, this project still needs contributions in particular areas, most notably performance. Any contribution, either in the form of a PR or a suggestion would be helpful. Cheers!

**Comment by peterbe** [comment]
@ajitid You're going to hate me for this but, on some basic tests I did, I'm now going to "reverse" my opinion on the default sort function in `fzf`. Check these out:

**sort=false**
<img width="418" alt="sort=false" src="https://user-images.githubusercontent.com/26739/127863578-4c6f20f5-0a04-4666-b439-d124ff45058a.png">

**sort=true**
<img width="409" alt="sort=true" src="https://user-images.githubusercontent.com/26739/127863597-0ec48f1b-68a5-466e-bb37-f2d05cc7b29e.png">

What happens is if you let the sort be by the documents that have any match, it misses out on those searches where a lot of the characters are together.

**Comment by peterbe** [comment]
I didn't for you to re-open it. What I meant was that after some more testing it certainly "feels" like it's better to use `fzf`'s sorting rather than relying on the natural order of the documents that it searches.

**Comment by ajitid** [comment]
Okay, I'll close it for now then.
