### ISSUE TITLE
[question] What does the postfix ! do?

### ISSUE THREAD

**Issue by dotnetCarpenter** [ajitid/fzf-for-js#30]
Hi, congratz on being on javascript weekly.

I skimmed the source and found [`str.split("").map((s) => s.codePointAt(0)!);`](https://github.com/ajitid/fzf-for-js/blob/dev/src/lib/runes.ts#L9).

What is the postfix `!` for? I tried to copy the line and are getting a syntax error in nodejs REPL.
Is it a typescript thing?

Cheers!

**Comment by ajitid** [comment]
Hey! Thanks, only yesterday I found out that this library is mentioned in the newsletter.

> What is the postfix ! for? ... Is it a typescript thing?

Yes, this is a TypeScript thing. `codePointAt` can [return `undefined`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt#return_value) if it doesn't find a character at that index. By appending `!` we are telling TypeScript that it is safe to assume that the returned value from `codePointAt` is a non-null, non-undefined value. 

Try hovering over `strOrNull` and `onlyStr` in this [TS playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBNBOB5eA5ArgGwwLjleAlmAOYwA+MYmG5MaYAJgKYBmRTDMAvJdQFChIscBgCeAZXzc8SVNQCEfIA) to see how it works.

Hope that helps!

**Comment by dotnetCarpenter** [comment]
Thanks @ajitid!
